### ISSUE TITLE
Fails to build from source

### ISSUE THREAD

**Issue by rekado** [Ibvt/RNAnue#13]
I'm using boost 1.77.0, segemehl 0.3.4, viennarna 2.4.18, seqan 3.0.3, and GCC 10.
Unfortunately RNAnue fails to build:

```
In file included from /gnu/store/gi3jk5wmnh6m7y55hqsd9jkwm1vvg4fh-seqan-3.0.3/include/seqan3/io/detail/record.hpp:19,
                 from /gnu/store/gi3jk5wmnh6m7y55hqsd9jkwm1vvg4fh-seqan-3.0.3/include/seqan3/io/sam_file/input.hpp:34,
                 from /gnu/store/gi3jk5wmnh6m7y55hqsd9jkwm1vvg4fh-seqan-3.0.3/include/seqan3/io/sam_file/all.hpp:37,
                 from /gnu/store/gi3jk5wmnh6m7y55hqsd9jkwm1vvg4fh-seqan-3.0.3/include/seqan3/io/alignment_file/all.hpp:16,
                 from /tmp/guix-build-rnanue-0.1.0-2.f8696dd.drv-0/source/source/../include/SplitReadCalling.hpp:26,
                 from /tmp/guix-build-rnanue-0.1.0-2.f8696dd.drv-0/source/source/SplitReadCalling.cpp:1:
/gnu/store/gi3jk5wmnh6m7y55hqsd9jkwm1vvg4fh-seqan-3.0.3/include/seqan3/io/record.hpp:354:30: note: declared here
  354 | SEQAN3_DEPRECATED_310 auto & get(record<field_types, field_ids> & r)
      |                              ^~~
/tmp/guix-build-rnanue-0.1.0-2.f8696dd.drv-0/source/source/SplitReadCalling.cpp:180:35: error: no matching function for call to ‘seqan3::cigar::cigar(<brace-enclosed initializer list>)’
  180 |                     seqan3::cigar cigarElement{cigarOpSize, cigarOp};
      |                                   ^~~~~~~~~~~~
In file included from /gnu/store/gi3jk5wmnh6m7y55hqsd9jkwm1vvg4fh-seqan-3.0.3/include/seqan3/alphabet/cigar/cigar.hpp:19,
                 from /gnu/store/gi3jk5wmnh6m7y55hqsd9jkwm1vvg4fh-seqan-3.0.3/include/seqan3/io/sam_file/detail/cigar.hpp:22,
                 from /gnu/store/gi3jk5wmnh6m7y55hqsd9jkwm1vvg4fh-seqan-3.0.3/include/seqan3/io/sam_file/format_bam.hpp:25,
                 from /gnu/store/gi3jk5wmnh6m7y55hqsd9jkwm1vvg4fh-seqan-3.0.3/include/seqan3/io/sam_file/all.hpp:34,
                 from /gnu/store/gi3jk5wmnh6m7y55hqsd9jkwm1vvg4fh-seqan-3.0.3/include/seqan3/io/alignment_file/all.hpp:16,
                 from /tmp/guix-build-rnanue-0.1.0-2.f8696dd.drv-0/source/source/../include/SplitReadCalling.hpp:26,
                 from /tmp/guix-build-rnanue-0.1.0-2.f8696dd.drv-0/source/source/SplitReadCalling.cpp:1:
```

**Comment by riasc** [comment]
Hi, thanks for creating this issue. Sorry for the late reply. There hasn't been much movement on this project as I'm not involved anymore. The problem is seqan 3.0.3 as there is some stuff deprecated. Will work on an update to 3.2 which probably involves some major rewriting. Thanks.
